spring:
  application:
    name: sample-springdata-service
    admin:
      enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/projectcs490j2?serverTimezone=America/Chicago
    username: cs490j2
    password: cs490j2
    driverClassName: com.mysql.cj.jdbc.Driver
  #  data: classpath:/data.sql
  #  initialization-mode: always
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  ###### Email Properties ######

  mail:
    host: smtp.gmail.com
    port: 587
    username: abc@gmail.com
    password: abc
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        confirmation:
          message: To confirm your account, please click here
          url: http://localhost:8081
    test-connection: false


